-- 회원 포인트/레벨 시스템
ALTER TABLE users ADD COLUMN points INT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN level TINYINT UNSIGNED NOT NULL DEFAULT 1;

CREATE TABLE IF NOT EXISTS point_logs (
  id         BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id    BIGINT UNSIGNED NOT NULL,
  points     INT NOT NULL,
  reason     VARCHAR(100) NOT NULL,
  ref_id     BIGINT UNSIGNED NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY idx_user (user_id)
);
